### ISSUE TITLE
老板，你这个Types是什么鬼。

### ISSUE THREAD

**Issue by zhaoxiuyu** [radnive/Flutter_DashedCircularProgressBar#1]
![image](https://github.com/radnive/Flutter_DashedCircularProgressBar/assets/16554580/416547ba-b4b2-4a75-8366-7bd5557857ef)

**Comment by radnive** [comment]
Sorry, it was my mistake that after removing the Types class (which included the TextStyles), I did not change the examples inside the README.md file.
